name: git_bindings
description: Provides a Git Higher level API using libgit2. It can be used
  with both iOS and Android.
version: 0.0.11
homepage: https://gitjournal.io

environment:
  sdk: ">=2.1.0 <3.0.0"
  flutter: ">=1.10.7 <2.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  test: ^1.5.1
  flutter_test:
    sdk: flutter
  flutter_driver:
    sdk: flutter

flutter:
  plugin:
    androidPackage: io.gitjournal.git_bindings
    pluginClass: GitBindingsPlugin
