name: git_bindings
description: Bindings for libgit2
version: 0.0.1
author: Vishesh Handa <me@vhanda.in>
homepage: https://gitjournal.io

environment:
  sdk: ">=2.1.0 <3.0.0"
  flutter: ">=1.10.7 <2.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  test: ^1.5.1
  flutter_test:
    sdk: flutter
  flutter_driver:
    sdk: flutter

flutter:
  plugin:
    androidPackage: io.gitjournal.git_bindings
    pluginClass: GitBindingsPlugin
